// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neuroability/Donate.tsx": () => import("../components/mockups/neuroability/Donate.tsx"),
  "./components/mockups/neuroability/Guides.tsx": () => import("../components/mockups/neuroability/Guides.tsx"),
  "./components/mockups/neuroability/Landing.tsx": () => import("../components/mockups/neuroability/Landing.tsx"),
  "./components/mockups/neuroability/Mentor.tsx": () => import("../components/mockups/neuroability/Mentor.tsx"),
  "./components/mockups/neuroability/Refer.tsx": () => import("../components/mockups/neuroability/Refer.tsx")
};
